config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  resources :users, only: [ :create ]
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # API routes
  post "v1/chat/completions", to: "api/v1/completions#create"
  post "v1/completions", to: "api/v1/completions#create"
  namespace :api do
    namespace :v1 do
      resources :completions, only: [ :create ]
      resources :files, only: [ :create ]
      resources :qnas, only: [ :create ]
      resources :texts, only: [ :create ]
      resources :websites, only: [ :create ]
    end
  end

  # User routes
  constraints Authentication::Authenticated do
    resources :accounts, only: [ :index, :edit, :update ]
    resources :api_tokens, only: [ :index, :create, :destroy ]
    resources :chats, only: [ :show, :create, :destroy ] do
      resources :messages, only: [ :create ]
    end
  end

  # Admin routes
  constraints Authentication::Admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"

    resource :settings, only: [ :show ]
    namespace :sources do
      resources :documents
      resources :qnas
      resources :texts
      resources :websites
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static#index"
end

app/models/text.rb
class Text < ApplicationRecord
  include Chunkable

  belongs_to :account

  def context
    data
  end
end

app/models/text/chunkable.rb
module Text::Chunkable
  extend ActiveSupport::Concern

  included do
    has_many :chunks, as: :chunkable, dependent: :destroy
  end

  def chunkify!
    separators = JSON.parse(ENV.fetch("SEPARATORS", [ "\n\n", "\n", " " ]).to_s)

    splitter = ::Baran::RecursiveCharacterTextSplitter.new(
      chunk_size: ENV.fetch("CHUNK_SIZE", 1000).to_i,
      chunk_overlap: ENV.fetch("CHUNK_OVERLAP", 200).to_i,
      separators:,
    )

    new_chunks = splitter.chunks(self.data)

    self.chunks.destroy_all

    new_chunks.each do |new_chunk|
      chunk = self.chunks.create!(account:, content: new_chunk.dig(:text))
      chunk.vectorize!
    end
  end
end

app/controllers/api/v1/texts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TextsController < ApplicationController
      def create
        text = @account.texts.new(text_params)

        if text.save
          AddTextJob.perform_later(text.id)

          response = {
            id: text.id
          }

          render json: response
        else
          render json: {}
        end
      end

      private

      def text_params
        params.permit(:data, :user)
      end
    end
  end
end

app/controllers/sources/documents_controller.rb
module Sources
  class DocumentsController < ApplicationController
    before_action :set_document, only: %i[ show edit update destroy ]

    # GET /documents or /documents.json
    def index
      @documents = Document.all
    end

    # GET /documents/1 or /documents/1.json
    def show
    end

    # GET /documents/new
    def new
      @document = Document.new
    end

    # GET /documents/1/edit
    def edit
    end

    # POST /documents or /documents.json
    def create
      @document = Document.new(document_params)

      respond_to do |format|
        if @document.save
          AddDocumentJob.perform_later(@document.id)
          format.html { redirect_to sources_document_url(@document), notice: "Document was successfully created." }
          format.json { render :show, status: :created, location: sources_document_url(@document) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /documents/1 or /documents/1.json
    def update
      respond_to do |format|
        if @document.update(document_params)
          AddDocumentJob.perform_later(@document.id)
          format.html { redirect_to sources_document_url(@document), notice: "Document was successfully updated." }
          format.json { render :show, status: :ok, location: sources_document_url(@document) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /documents/1 or /documents/1.json
    def destroy
      @document.destroy!

      respond_to do |format|
        format.html { redirect_to sources_documents_url, notice: "Document was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      permitted = params.require(:document).permit(:account_id, :title, :file)
      permitted = permitted.merge(account: Current.account) unless permitted.has_key?(:account_id)
      permitted
    end
  end
end

app/controllers/sources/qnas_controller.rb
module Sources
  class QnasController < ApplicationController
    before_action :set_qna, only: %i[ show edit update destroy ]

    # GET /qnas or /qnas.json
    def index
      @qnas = Qna.all
    end

    # GET /qnas/1 or /qnas/1.json
    def show
    end

    # GET /qnas/new
    def new
      @qna = Qna.new
    end

    # GET /qnas/1/edit
    def edit
    end

    # POST /qnas or /qnas.json
    def create
      @qna = Qna.new(qna_params)

      respond_to do |format|
        if @qna.save
          AddQnaJob.perform_later(@qna.id)
          format.html { redirect_to sources_qna_url(@qna), notice: "Q&A was successfully created." }
          format.json { render :show, status: :created, location: sources_qna_url(@qna) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @qna.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /qnas/1 or /qnas/1.json
    def update
      respond_to do |format|
        if @qna.update(qna_params)
          AddQnaJob.perform_later(@qna.id)
          format.html { redirect_to sources_qna_url(@qna), notice: "Q&A was successfully updated." }
          format.json { render :show, status: :ok, location: sources_qna_url(@qna) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @qna.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /qnas/1 or /qnas/1.json
    def destroy
      @qna.destroy!

      respond_to do |format|
        format.html { redirect_to sources_qnas_url, notice: "Q&A was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_qna
      @qna = Qna.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qna_params
      params.require(:qna).permit(:account_id, :question, :answer)
    end
  end
end

app/controllers/sources/texts_controller.rb
module Sources
  class TextsController < ApplicationController
    before_action :set_text, only: %i[ show edit update destroy ]

    # GET /texts or /texts.json
    def index
      @texts = Text.all
    end

    # GET /texts/1 or /texts/1.json
    def show
    end

    # GET /texts/new
    def new
      @text = Text.new
    end

    # GET /texts/1/edit
    def edit
    end

    # POST /texts or /texts.json
    def create
      @text = Text.new(text_params)

      respond_to do |format|
        if @text.save
          AddTextJob.perform_later(@text.id)
          format.html { redirect_to sources_text_url(@text), notice: "Text was successfully created." }
          format.json { render :show, status: :created, location: @text }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @text.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /texts/1 or /texts/1.json
    def update
      respond_to do |format|
        if @text.update(text_params)
          AddTextJob.perform_later(@text.id)
          format.html { redirect_to sources_text_url(@text), notice: "Text was successfully updated." }
          format.json { render :show, status: :ok, location: @text }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @text.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /texts/1 or /texts/1.json
    def destroy
      @text.destroy!

      respond_to do |format|
        format.html { redirect_to sources_texts_url, notice: "Text was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def text_params
      params.require(:text).permit(:account_id, :data)
    end
  end
end

app/controllers/sources/websites_controller.rb
module Sources
  class WebsitesController < ApplicationController
    before_action :set_website, only: %i[ show edit update destroy ]

    # GET /websites or /websites.json
    def index
      @websites = Website.all.order(:url)
    end

    # GET /websites/1 or /websites/1.json
    def show
    end

    # GET /websites/new
    def new
      @website = Website.new
    end

    # GET /websites/1/edit
    def edit
    end

    # POST /websites or /websites.json
    def create
      @website = Website.new(website_params)

      respond_to do |format|
        if @website.save
          CrawlWebsiteUrlsJob.perform_later(@website.id)
          format.html { redirect_to sources_website_url(@website), notice: "Website was successfully created." }
          format.json { render :show, status: :created, location: @website }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @website.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /websites/1 or /websites/1.json
    def update
      respond_to do |format|
        if @website.update(website_params)
          CrawlWebsiteUrlJob.perform_later(@website.id)
          format.html { redirect_to sources_website_url(@website), notice: "Website was successfully updated." }
          format.json { render :show, status: :ok, location: @website }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @website.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /websites/1 or /websites/1.json
    def destroy
      @website.destroy!

      respond_to do |format|
        format.html { redirect_to sources_websites_url, notice: "Website was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.require(:website).permit(:account_id, :data, :url)
    end
  end
end

app/controllers/sources_controller.rb
# frozen_string_literal: true

class SourcesController < ApplicationController
  def show
  end
end

app/views/sources/texts/_form.html.erb
<%= form_with(model: [:sources, text]) do |form| %>
  <div class="n-form-field">
    <%= form.label :data, "Text", class: "n-label" %>
    <%= form.text_area :data, rows: 18, class: "n-textarea" %>
  </div>

  <div class="n-form-field">
    <%= form.label :account_id, "Account", class: "n-label" %>
    <%= form.collection_select :account_id,
                           Current.user.accounts,
                           :id,
                           :name,
                           { prompt: true, required: true },
                           { class: "n-select" } %>
  </div>

  <div class="n-form-actions">
    <%= form.submit "Save", class: "n-btn-primary" %>
  </div>
<% end %>

app/views/sources/texts/edit.html.erb
<section>
  <div class="n-form-container">
    <h2 class="n-form-title">Edit Text #<%= @text.id %></h2>
    <%= render "form", text: @text %>
  </div>
</section>

app/views/sources/texts/index.html.erb
<section>
  <div class="n-main-container">
    <div class="n-title-container">
      <p class="n-title">Texts</p>
      <%= link_to "New text", new_sources_text_path, class: "n-btn-primary" %>
    </div>
    <div class="n-table-container">
      <table class="n-table">
        <thead class="n-table-head">
          <tr>
            <th scope="col" class="n-table-head-th">
              Text
            </th>
            <th scope="col" class="table-header-th">
              Account
            </th>
            <th scope="col" class="n-table-head-th">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% @texts.each do |text| %>
            <tr class="n-tr">
              <td class="n-td">
                <%= text.data %>
              </td>
              <td class="n-td">
                <%= text.account&.name %>
              </td>
              <td class="n-td">
                <%= link_to "Edit", edit_sources_text_path(text), class: "n-btn-primary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/sources/texts/new.html.erb
<section>
  <div class="n-form-container">
    <h2 class="n-form-title">New Text</h2>
    <%= render "form", text: @text %>
  </div>
</section>

app/views/sources/texts/show.html.erb
<section>
  <div class="n-form-container">
    <h2 class="n-form-title">Text #<%= @text.id %></h2>
    <p class="n-form-content">
      <%= @text.data %>
    </p>
    <div class="flex items-center space-x-4">
      <%= link_to edit_sources_text_path(@text), class: "n-btn-primary" do %>
        <svg
          aria-hidden="true"
          class="mr-1 -ml-1 w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        ><path
            d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"
          ></path><path
            fill-rule="evenodd"
            d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"
            clip-rule="evenodd"
          ></path></svg>
        Edit
      <% end %>
      <%= button_to sources_text_path(@text), method: :delete, data: { turbo_confirm: "Are your sure?" }, class: "n-btn-danger" do %>
        <svg
          aria-hidden="true"
          class="w-5 h-5 mr-1.5 -ml-1"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        ><path
            fill-rule="evenodd"
            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
            clip-rule="evenodd"
          ></path></svg>
        Delete
      <% end %>
    </div>
  </div>
</section>