config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  resources :users, only: [ :create ]
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # API routes
  post "v1/chat/completions", to: "api/v1/completions#create"
  post "v1/completions", to: "api/v1/completions#create"
  namespace :api do
    namespace :v1 do
      resources :completions, only: [ :create ]
      resources :files, only: [ :create ]
      resources :qnas, only: [ :create ]
      resources :texts, only: [ :create ]
      resources :websites, only: [ :create ]
    end
  end

  # User routes
  constraints Authentication::Authenticated do
    resources :accounts, only: [ :index, :edit, :update ]
    resources :api_tokens, only: [ :index, :create, :destroy ]
    resources :chats, only: [ :show, :create, :destroy ] do
      resources :messages, only: [ :create ]
    end
  end

  # Admin routes
  constraints Authentication::Admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"

    resource :settings, only: [ :show ]
    namespace :sources do
      resources :documents
      resources :qnas
      resources :texts
      resources :websites
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :owner, class_name: "User"

  has_many :account_users, dependent: :destroy
  has_many :users, through: :account_users
  has_many :chats, dependent: :destroy
  has_many :chunks, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :qnas, dependent: :destroy
  has_many :texts, dependent: :destroy
  has_many :websites, dependent: :destroy

  def augmented_context
    context = []
    context << texts.map(&:context)
    context << qnas.map(&:context)
    context << documents.map(&:context)
    context
  end

  def default_context
    context = []
    context << texts.map(&:context)
    context
  end
end

app/models/account_user.rb
class AccountUser < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/api_token.rb
class ApiToken < ApplicationRecord
  belongs_to :account
  belongs_to :user

  has_secure_token :token

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :documents, dependent: :nullify
end

app/models/chat.rb
class Chat < ApplicationRecord
  include Completionable
  include Infomaniak
  include Ollama

  belongs_to :account
  belongs_to :user
  has_many :messages, dependent: :destroy

  def first_question
    messages.where(role: "user").order(:created_at).first&.content
  end

  def last_question
    messages.where(role: "user").order(:created_at).last&.content
  end

  def messages_hash
    messages.order(:response_number).map do |message|
      {
        role: message.role,
        content: message.content
      }
    end
  end

  def response_number
    messages.count
  end
end

app/models/chunk.rb
class Chunk < ApplicationRecord
  include Vectorizable

  belongs_to :account
  belongs_to :chunkable, polymorphic: true

  def augmented_context
    chunkable.context
  end

  def context
    content
  end
end

app/models/credential.rb
class Credential < ApplicationRecord
  belongs_to :user, validate: true

  validates :provider, presence: true
  validates :uid, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :impersonated_user

  def account = user.first_account
  def user = true_user
  def true_user = session&.user
end

app/models/document.rb
class Document < ApplicationRecord
  include Chunkable, Parsable, Vectorizable

  belongs_to :account, optional: true
  belongs_to :author, optional: true
  has_one_attached :file

  validates :file, presence: true

  def context
    content
  end

  def titlize!
    update(title: file.filename.to_s)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  enum :role, { system: 0, assistant: 10, user: 20 }

  belongs_to :chat

  after_create_commit -> { broadcast_created }
  after_update_commit -> { broadcast_updated }

  def broadcast_created
    broadcast_append_later_to(
      "#{dom_id(chat)}_messages",
      partial: "messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(chat)}_messages"
    )
  end

  def broadcast_updated
    broadcast_append_to(
      "#{dom_id(chat)}_messages",
      partial: "messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(chat)}_messages"
    )
  end

  def similar_authors
    Author.where(id: similar_documents.pluck(:author_id))
  end

  def similar_chunks
    Chunk.where(id: similar_chunk_ids.uniq)
  end

  def similar_documents
    Document.where(id: similar_document_ids.uniq)
  end

  def to_html
    Commonmarker.to_html(content)
  end
end

app/models/qna.rb
class Qna < ApplicationRecord
  include Chunkable

  belongs_to :account

  def context
    [ question, answer ].join("\n")
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/text.rb
class Text < ApplicationRecord
  include Chunkable

  belongs_to :account

  def context
    data
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :account_users, dependent: :destroy
  has_many :accounts, through: :account_users
  has_many :api_tokens, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :credentials, dependent: :destroy
  has_many :sessions, dependent: :destroy

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :password,
    presence: true,
    length: { minimum: 12 },
    on: :create

  def first_account
    accounts.order(:created_at).first
  end
end

app/models/website.rb
class Website < ApplicationRecord
  include Chunkable
  include Crawlable

  belongs_to :account

  def context
    data
  end

  def title
    return unless data.present?

    document = Commonmarker.parse(data)

    document.walk do |node|
      if node.type == :heading && node.header_level == 1
        return node.first_child.string_content
      end
    end

    nil
  end

  def to_html
    Commonmarker.to_html(data)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[show destroy]

  def show
  end

  def create
    @chat = Current.user.chats.create(account: Current.account)
    redirect_to @chat
  end

  def destroy
    @chat.destroy
    redirect_to root_path
  end

  private

  def set_chat
    @chat = Current.user.chats.find(params[:id])
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  def show
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  allow_unauthenticated_access only: [ :index ]

  def index
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  before_action :check_allowed_registrations

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    # Make the first user admin
    @user.admin = true if User.all.count.eql?(0)

    if @user.save
      user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])
      start_new_session_for user
      redirect_to root_path, notice: "Welcome to Nosia!"
    else
      redirect_to root_path, alert: "Try another email address or password with at least 12 characters."
    end
  end

  private

  def check_allowed_registrations
    redirect_to root_path, alert: "Registrations are closed." unless ActiveModel::Type::Boolean.new.cast(ENV.fetch("REGISTRATIONS_ALLOWED", true))
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def registrations_allowed?
    ActiveModel::Type::Boolean.new.cast(ENV.fetch("REGISTRATIONS_ALLOWED", true))
  end
end

app/views/settings/show.html.erb
<section>
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="sm:flex sm:items-center sm:justify-between sm:gap-4">
      <p class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Settings</p>
    </div>

    <div
      class="
        mb-4 mt-6 grid grid-cols-1 gap-4 text-center sm:mt-8 sm:grid-cols-2 lg:mb-0
        lg:grid-cols-4 xl:gap-8
      "
    >
      <%= link_to sources_documents_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 0 1-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 0 1 1.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 0 0-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 0 1-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 0 0-3.375-3.375h-1.5a1.125 1.125 0 0 1-1.125-1.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H9.75"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">Documents</p>
      <% end %>

      <%= link_to sources_texts_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">Texts</p>
      <% end %>

      <%= link_to sources_qnas_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">Q&As</p>
      <% end %>

      <%= link_to sources_websites_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M3 8.25V18a2.25 2.25 0 0 0 2.25 2.25h13.5A2.25 2.25 0 0 0 21 18V8.25m-18 0V6a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 6v2.25m-18 0h18M5.25 6h.008v.008H5.25V6ZM7.5 6h.008v.008H7.5V6Zm2.25 0h.008v.008H9.75V6Z"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">Websites</p>
      <% end %>

      <%= link_to accounts_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="m21 7.5-9-5.25L3 7.5m18 0-9 5.25m9-5.25v9l-9 5.25M3 7.5l9 5.25M3 7.5v9l9 5.25m0-9v9"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">Accounts</p>
      <% end %>

      <%= link_to api_tokens_path, class: "
          grid place-content-center space-y-6 overflow-hidden rounded-lg border
          border-gray-200 bg-white p-6 hover:bg-gray-100 dark:border-gray-700
          dark:bg-gray-800 dark:hover:bg-gray-700
        " do %>
        <svg
          class="mx-auto h-14 w-14 text-gray-400 dark:text-gray-500"
          data-slot="icon"
          aria-hidden="true"
          fill="none"
          stroke-width="1.5"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="m6.75 7.5 3 2.25-3 2.25m4.5 0h3m-9 8.25h13.5A2.25 2.25 0 0 0 21 18V6a2.25 2.25 0 0 0-2.25-2.25H5.25A2.25 2.25 0 0 0 3 6v12a2.25 2.25 0 0 0 2.25 2.25Z"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></path>
        </svg>
        <p class="text-lg font-semibold text-gray-900 dark:text-white">API tokens</p>
      <% end %>
    </div>
  </div>
</section>